server:
  port: 8781
spring:
  application:
    name: consumer-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/,http://eureka1:8761/eureka/
management:
  server:
    port: 9001
  endpoints:
    web:
#      base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点
mytest:
  bus:
    rabbit:
      text: 123
