#single eureka client
#server:
#  port: 8771
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#spring:
#  application:
#    name: eureka-client

#multiple eureka client
spring:
  profiles:
    active: native
  application:
    name: eureka-client
server:
  port: 8772
eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/,http://eureka1:8761/eureka/